-- =============================================================================
-- CLINICAL DOCUMENTS AI-POWERED EXTRACTION - DYNAMIC PIPELINE SETUP
-- =============================================================================
-- AUTHORITATIVE SOURCE: references/document_type_specs.yaml
--   This YAML spec file defines doc types, extraction fields, prompts, and PHI
--   flags. The config table (CLINICAL_DOCS_EXTRACTION_CONFIG) is DERIVED from
--   these specs — not the other way around.
--
-- Two CKE (Cortex Knowledge Extension) layers feed the skill at runtime:
--   1. Schema CKE  — CLINICAL_DOCS_MODEL_SEARCH_SVC (auto-generated by Step 7)
--      Answers: "What tables exist?" "Which columns contain PHI?"
--   2. Spec CKE    — CLINICAL_DOCS_SPECS_SEARCH_SVC (auto-generated by Step 7b)
--      Answers: "What fields does a discharge summary have?"
--
-- Flow: document_type_specs.yaml -> extraction_config CSV / direct INSERT ->
--       config table -> GENERATE_DYNAMIC_OBJECTS() ->
--       seeds classification/extraction configs, updates classification question
--       via LISTAGG, generates pivot views, refresh task, Semantic View,
--       refreshes Schema CKE corpus, and refreshes Spec CKE corpus.
--
-- Adding a new doc type:
--   1. Add entry to references/document_type_specs.yaml (authoritative spec)
--   2. Seed config table from spec (INSERT rows or load CSV)
--   3. CALL GENERATE_DYNAMIC_OBJECTS() — one call does everything
-- See references/metadata_as_cke.md for the full CKE-driven pattern.
-- =============================================================================
--
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- CLI INCOMPATIBILITY WARNING
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- This script is designed for Snowsight worksheet execution (single session).
-- It WILL NOT work with `snow sql -f` due to:
--   1. Session variables ($V_DB, $V_SCHEMA) are lost between semicolons
--   2. EXECUTE IMMEDIATE with || concatenation gets split at wrong boundaries
--   3. Nested $$ delimiters in stored procedure bodies cause parse errors
--   4. Shell interprets $V_DB as a shell variable (empty) in snow sql -q
--
-- FOR CLI / CoCo EXECUTION:
--   1. Replace all $V_DB, $V_SCHEMA, $V_WAREHOUSE with hardcoded values
--   2. Write each STEP section to a separate temp file
--   3. Execute via: snow sql -c {connection} -f /tmp/step_N.sql
--   4. For GENERATE_DYNAMIC_OBJECTS proc, hardcode v_fqn in the proc body
--
-- The snowflake_sql_execute CoCo tool supports the connection parameter
-- for targeting non-default connections.
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--
-- EXECUTION NOTES (for CoCo agents executing this script):
-- -------------------------------------------------------
-- 1. IDENTIFIER() LIMITATION: Snowflake's IDENTIFIER() function does NOT support
--    expression concatenation (|| operator) inside DDL statements like
--    CREATE SCHEMA, CREATE STAGE, CREATE TABLE. It only works with single
--    session variables (e.g., IDENTIFIER($V_DB)) or simple string literals.
--    WORKAROUND: This script uses EXECUTE IMMEDIATE with string concatenation
--    for all DDL that requires multi-part names (db.schema.object).
--
-- 2. EXECUTION METHOD: When executing via CoCo, write each STEP section to a
--    temp file with hardcoded FQN values, then run via snow sql -c {connection} -f.
--    DO NOT use `snow sql -f` for the entire file — it WILL fail on
--    multi-statement batches with session variables and EXECUTE IMMEDIATE blocks.
--    Instead, run each section (delimited by STEP comments) as a separate call.
--
-- 3. RECOMMENDED EXECUTION ORDER:
--    a. Run STEP 0 (variables + database/schema/warehouse creation)
--    b. Run STEP 1 (stage)
--    c. Run STEP 2 + 2b + 2c (config tables + model reference table + specs reference table)
--    d. Run STEP 2d (Cortex Search Services — requires tables from 2b/2c to exist)
--    e. Run STEP 3 (pipeline tables) — can split into 2 batches if needed
--    f. Run STEP 4 (stream)
--    g. Run STEP 5 (UDFs) — MUST use snowflake_sql_execute, not snow sql CLI
--    h. Run STEP 6 (GENERATE_DYNAMIC_OBJECTS proc) — same, use snowflake_sql_execute
--
-- 4. QUOTING: The EXECUTE IMMEDIATE blocks in Steps 5 and 6 contain deeply
--    nested quote escaping (4+ levels). These WILL break if passed through
--    shell quoting (snow sql -q "..."). Always use snowflake_sql_execute tool
--    or a Snowflake worksheet for these sections.
-- =============================================================================

-- ======================== CONFIGURATION VARIABLES ============================
-- IMPORTANT: Update these before running. V_WAREHOUSE will be CREATED at 3X-Large
-- if it does not exist. To use an existing warehouse, change V_WAREHOUSE below.
SET V_DB              = 'HCLS_COCO_TEST_DB';
SET V_SCHEMA          = 'CLINICAL_DOCS_ACTIVATION';
SET V_WAREHOUSE       = 'DEMO_BUILD_WH';
SET V_STAGE           = 'INTERNAL_CLINICAL_DOCS_STAGE';
-- =============================================================================

-- =============================================================================
-- STEP 0: DATABASE, SCHEMA, WAREHOUSE (run first, separately)
-- =============================================================================
-- NOTE: IDENTIFIER() does NOT support concatenation in CREATE SCHEMA / CREATE DATABASE.
-- Use EXECUTE IMMEDIATE to build the fully-qualified DDL string dynamically.
-- =============================================================================

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($V_WAREHOUSE)
    WAREHOUSE_SIZE = '3X-LARGE'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 600
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Clinical Documents AI processing';

USE WAREHOUSE IDENTIFIER($V_WAREHOUSE);

CREATE DATABASE IF NOT EXISTS IDENTIFIER($V_DB);

EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || $V_DB || '.' || $V_SCHEMA;

USE DATABASE IDENTIFIER($V_DB);
USE SCHEMA IDENTIFIER($V_SCHEMA);

-- =============================================================================
-- STEP 1: INTERNAL STAGE FOR DOCUMENTS
-- =============================================================================
EXECUTE IMMEDIATE
    'CREATE STAGE IF NOT EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.' || $V_STAGE ||
    ' DIRECTORY = (ENABLE = TRUE)' ||
    ' ENCRYPTION = (TYPE = ''SNOWFLAKE_SSE'')' ||
    ' COMMENT = ''Internal stage for clinical document PDFs''';

-- =============================================================================
-- STEP 2: EXTRACTION CONFIG TABLE (pipeline config from CSV)
-- =============================================================================
EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_EXTRACTION_CONFIG (
    CONFIG_TYPE VARCHAR(20) NOT NULL,
    DOC_TYPE VARCHAR(200) NOT NULL,
    FIELD_NAME VARCHAR(100) NOT NULL,
    EXTRACTION_QUESTION VARCHAR(1000) NOT NULL,
    TARGET_COLUMN VARCHAR(100),
    DATA_TYPE VARCHAR(100),
    DISPLAY_ORDER NUMBER(38,0),
    VIEW_NAME VARCHAR(200),
    IS_IDENTITY_FIELD VARCHAR(20)
)';

-- =============================================================================
-- STEP 2b: MODEL REFERENCE TABLE (schema docs — for DATA_MODEL_KNOWLEDGE Cortex Search)
-- =============================================================================
EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || $V_DB || '.DATA_MODEL_KNOWLEDGE';

EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_MODEL_REFERENCE (
    SEARCH_TEXT VARCHAR(4000),
    TABLE_NAME VARCHAR(200) NOT NULL,
    COLUMN_NAME VARCHAR(200) NOT NULL,
    DATA_TYPE VARCHAR(100),
    DOMAIN_TAG VARCHAR(100),
    CATEGORY VARCHAR(100),
    DESCRIPTION VARCHAR(2000),
    CONSTRAINTS VARCHAR(500),
    CONTAINS_PHI VARCHAR(20),
    RELATIONSHIPS VARCHAR(500)
)';

-- STEP 2c: SPEC REFERENCE TABLE (doc type specs — for Spec CKE Cortex Search)
-- Populated by GENERATE_DYNAMIC_OBJECTS() Step 7b from the same config table.
-- Enables dynamic discovery: "What fields does a discharge summary have?"
-- Source of truth: references/document_type_specs.yaml
EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_SPECS_REFERENCE (
    SEARCH_TEXT VARCHAR(4000),
    DOC_TYPE VARCHAR(200) NOT NULL,
    FIELD_NAME VARCHAR(200) NOT NULL,
    EXTRACTION_QUESTION VARCHAR(1000),
    DATA_TYPE VARCHAR(100),
    DISPLAY_ORDER NUMBER(38,0),
    VIEW_NAME VARCHAR(200),
    IS_IDENTITY_FIELD VARCHAR(20),
    CONTAINS_PHI VARCHAR(20),
    DESCRIPTION VARCHAR(2000)
)';

-- =============================================================================
-- STEP 2d: CORTEX SEARCH SERVICES (CKE layers — query tables at runtime)
-- =============================================================================
-- Schema CKE: skills query "What tables exist? Which columns contain PHI?"
-- Populated by GENERATE_DYNAMIC_OBJECTS() Step 7 from config table.
EXECUTE IMMEDIATE
'CREATE OR REPLACE CORTEX SEARCH SERVICE ' || $V_DB || '.DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_MODEL_SEARCH_SVC
    ON search_text
    ATTRIBUTES table_name, column_name, data_type, category, contains_phi
    WAREHOUSE = ' || $V_WAREHOUSE || '
    TARGET_LAG = ''1 day''
AS (
    SELECT search_text, table_name, column_name, data_type, domain_tag,
           category, description, constraints, contains_phi, relationships
    FROM ' || $V_DB || '.DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_MODEL_REFERENCE
)';

-- Spec CKE: skills query "What fields does a discharge summary have?"
-- Populated by GENERATE_DYNAMIC_OBJECTS() Step 7b from config table.
-- Source of truth: references/document_type_specs.yaml
EXECUTE IMMEDIATE
'CREATE OR REPLACE CORTEX SEARCH SERVICE ' || $V_DB || '.DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_SPECS_SEARCH_SVC
    ON search_text
    ATTRIBUTES doc_type, field_name, data_type, contains_phi
    WAREHOUSE = ' || $V_WAREHOUSE || '
    TARGET_LAG = ''1 day''
AS (
    SELECT search_text, doc_type, field_name, extraction_question,
           data_type, display_order, view_name, is_identity_field,
           contains_phi, description
    FROM ' || $V_DB || '.DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_SPECS_REFERENCE
)';

-- =============================================================================
-- STEP 3: DOC-TYPE-AGNOSTIC TABLES (EAV pattern — never changes per doc type)
-- =============================================================================
EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.' || $V_SCHEMA || '.DOCUMENT_HIERARCHY (
    DOCUMENT_RELATIVE_PATH VARCHAR(500) NOT NULL,
    DOCUMENT_STAGE VARCHAR(500) NOT NULL,
    DOC_PAGES NUMBER(38,0),
    DOC_SIZE_MB FLOAT,
    PARENT_DOCUMENT_RELATIVE_PATH VARCHAR(500),
    PARENT_DOCUMENT_STAGE VARCHAR(500),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SPLIT_REASON VARCHAR(100),
    PARENT_DOCUMENT_SPLIT_SEQUENCE NUMBER(38,0)
)';

EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.' || $V_SCHEMA || '.DOCS_PARSE_OUTPUT (
    DOCUMENT_RELATIVE_PATH VARCHAR(500) NOT NULL,
    DOCUMENT_STAGE VARCHAR(500) NOT NULL,
    PARENT_DOCUMENT_RELATIVE_PATH VARCHAR(500),
    PAGE_NUMBER_IN_PARENT NUMBER(38,0) NOT NULL,
    PAGE_CONTENT VARCHAR(16777216) NOT NULL,
    DOC_TOTAL_PAGES NUMBER(38,0),
    PARSE_MODE VARCHAR(20),
    EXTRACT_IMAGES BOOLEAN DEFAULT FALSE,
    PARSE_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
)';

EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.' || $V_SCHEMA || '.DOC_CLASSIFICATION_METADATA_ROWS (
    DOCUMENT_RELATIVE_PATH VARCHAR(500) NOT NULL,
    DOCUMENT_STAGE VARCHAR(500) NOT NULL,
    FIELD_NAME VARCHAR(100) NOT NULL,
    FIELD_VALUE VARCHAR(5000),
    EXTRACTION_TIMESTAMP TIMESTAMP_LTZ(9),
    DOC_CATEGORY VARCHAR(5000)
)';

EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.' || $V_SCHEMA || '.DOC_TYPE_SPECIFIC_VALUES_EXTRACT_OUTPUT (
    DOCUMENT_RELATIVE_PATH VARCHAR(500) NOT NULL,
    DOCUMENT_STAGE VARCHAR(500) NOT NULL,
    DOCUMENT_CLASSIFICATION VARCHAR(500) NOT NULL,
    FIELD_NAME VARCHAR(100) NOT NULL,
    FIELD_VALUE VARCHAR(5000),
    EXTRACTION_TIMESTAMP TIMESTAMP_LTZ(9)
)';

EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCUMENTS_RAW_CONTENT (
    DOCUMENT_RELATIVE_PATH VARCHAR(500),
    DOCUMENT_STAGE VARCHAR(500),
    PAGE_NUMBER_IN_PARENT NUMBER(38,0),
    DOCUMENT_CLASSIFICATION VARCHAR(500),
    PATIENT_NAME VARCHAR(16777216),
    MRN VARCHAR(16777216),
    PAGE_CONTENT VARCHAR(16777216),
    DOC_TOTAL_PAGES NUMBER(38,0),
    PRESIGNED_URL VARCHAR(16777216),
    STAGE_FILE_URL VARCHAR(16777216),
    URL_GENERATED_AT TIMESTAMP_LTZ(9)
)';

EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.' || $V_SCHEMA || '.DOCUMENT_CLASSIFICATION_EXTRACTION_FIELD_CONFIG (
    FIELD_NAME VARCHAR(100) NOT NULL PRIMARY KEY,
    EXTRACTION_QUESTION VARCHAR(1000),
    TARGET_COLUMN VARCHAR(100),
    DATA_TYPE VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DISPLAY_ORDER NUMBER(38,0),
    CREATED_TIMESTAMP TIMESTAMP_LTZ(3),
    UPDATED_TIMESTAMP TIMESTAMP_LTZ(3)
)';

EXECUTE IMMEDIATE
'CREATE OR REPLACE TABLE ' || $V_DB || '.' || $V_SCHEMA || '.DOC_TYPE_SPECIFIC_EXTRACTION_CONFIG (
    DOCUMENT_CLASSIFICATION VARCHAR(500) NOT NULL,
    FIELD_NAME VARCHAR(100) NOT NULL,
    EXTRACTION_QUESTION VARCHAR(1000) NOT NULL,
    DATA_TYPE VARCHAR(50) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DISPLAY_ORDER NUMBER(38,0),
    CREATED_TIMESTAMP TIMESTAMP_LTZ(9),
    UPDATED_TIMESTAMP TIMESTAMP_LTZ(9)
)';

-- =============================================================================
-- STEP 4: STREAM
-- =============================================================================
EXECUTE IMMEDIATE
    'CREATE OR REPLACE STREAM ' || $V_DB || '.' || $V_SCHEMA || '.DOCS_PARSE_OUTPUT_STREAM' ||
    ' ON TABLE ' || $V_DB || '.' || $V_SCHEMA || '.DOCS_PARSE_OUTPUT' ||
    ' APPEND_ONLY = TRUE';

-- =============================================================================
-- STEP 5: UDFs (config-driven — read from config tables at runtime)
-- NOTE: BUILD_DOCUMENT_CLASIFICATION_EXTRACTION_JSON returns an OBJECT of
--   {FIELD_NAME: EXTRACTION_QUESTION} pairs from the classification config.
--   This UDF is used by the EXTRACT_DOCUMENT_CLASSIFICATION_METADATA proc to
--   build the AI_COMPLETE classification prompt (NOT for AI_EXTRACT responseFormat).
--   The proc joins the classification prompt with AI_PARSE_DOCUMENT output text.
--   BUILD_DOC_TYPE_EXTRACTION_JSON is still used with AI_EXTRACT for field extraction.
-- =============================================================================
EXECUTE IMMEDIATE
$$
BEGIN
    LET v_fqn_prefix := $V_DB || '.' || $V_SCHEMA;

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE FUNCTION ' || :v_fqn_prefix || '.BUILD_DOCUMENT_CLASIFICATION_EXTRACTION_JSON()
    RETURNS OBJECT LANGUAGE SQL AS ''
        SELECT OBJECT_AGG(FIELD_NAME, TO_VARIANT(EXTRACTION_QUESTION))
        FROM ' || :v_fqn_prefix || '.DOCUMENT_CLASSIFICATION_EXTRACTION_FIELD_CONFIG WHERE IS_ACTIVE = TRUE
    ''';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE FUNCTION ' || :v_fqn_prefix || '.BUILD_DOC_TYPE_EXTRACTION_JSON(DOC_TYPE VARCHAR)
    RETURNS OBJECT LANGUAGE SQL AS ''
        SELECT OBJECT_AGG(FIELD_NAME, TO_VARIANT(EXTRACTION_QUESTION))
        FROM ' || :v_fqn_prefix || '.DOC_TYPE_SPECIFIC_EXTRACTION_CONFIG
        WHERE DOCUMENT_CLASSIFICATION ILIKE DOC_TYPE AND IS_ACTIVE = TRUE
    ''';
END;
$$;

-- NOTE: IDENTIFIER() works for CREATE FUNCTION (unlike CREATE TABLE/SCHEMA/STAGE).
-- We use it here because the Python body contains single quotes that conflict with
-- EXECUTE IMMEDIATE string quoting. IDENTIFIER() avoids that nesting issue.
CREATE OR REPLACE FUNCTION IDENTIFIER($V_DB || '.' || $V_SCHEMA || '.INJECT_IMAGE_DESCRIPTIONS')(PAGE_CONTENT VARCHAR, IMAGE_DATA ARRAY)
RETURNS VARCHAR LANGUAGE PYTHON RUNTIME_VERSION = '3.10' HANDLER = 'inject_descriptions' AS '
def inject_descriptions(page_content, image_data):
    if not page_content or not image_data:
        return page_content
    enhanced_content = page_content
    for img in image_data:
        if not img or "image_id" not in img:
            continue
        image_id = img["image_id"]
        description = img.get("description", "")
        if not description or description == "None":
            continue
        search_pattern = "![" + image_id + "](" + image_id + ")"
        if search_pattern in enhanced_content:
            replacement = search_pattern + chr(10) + chr(10) + "**IMAGE DESCRIPTION:** " + description + chr(10)
            enhanced_content = enhanced_content.replace(search_pattern, replacement, 1)
    return enhanced_content
';

-- =============================================================================
-- STEP 6: DYNAMIC GENERATOR PROCEDURE
-- =============================================================================
-- Reads CLINICAL_DOCS_EXTRACTION_CONFIG (loaded from extraction_config CSV) and:
--   1.  Seeds DOCUMENT_CLASSIFICATION_EXTRACTION_FIELD_CONFIG (CLASSIFICATION rows)
--   1b. Updates classification question with dynamic type list via LISTAGG
--   2.  Seeds DOC_TYPE_SPECIFIC_EXTRACTION_CONFIG (EXTRACTION rows)
--   3.  Generates pivot views dynamically for each doc type (from VIEW_NAME column)
--       Uses IS_IDENTITY_FIELD to resolve identity columns per doc type
--   4.  Generates MRN_PATIENT_MAPPING view
--   5.  Generates the refresh task with dynamic JOINs to all discovered pivot views
--   6.  Generates CLINICAL_DOCS_SEMANTIC_VIEW with DIMENSIONS + METRICS
--   7.  Refreshes DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_MODEL_REFERENCE from config table (Schema CKE)
--   7b. Refreshes DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_SPECS_REFERENCE from config table (Spec CKE)
--
-- IMPORTANT — EXECUTION CONSTRAINTS:
--   * This block CANNOT be run via `snow sql -f` (session variables + $$ conflict).
--   * This block CANNOT use nested $$ (Snowflake does not support it).
--   * The proc is FULLY PARAMETERIZED — pass db, schema, warehouse, stage as args:
--     CALL GENERATE_DYNAMIC_OBJECTS('MY_DB', 'MY_SCHEMA', 'MY_WH', 'MY_STAGE')
--     No hardcoded {db}/{schema} placeholders to substitute at creation time.
--   * Cursors use RESULTSET pattern inside BEGIN (EXECUTE IMMEDIATE → RESULTSET
--     → CURSOR FOR rs → FOR rec IN cur) to avoid the DECLARE cursor limitation
--     where variables are not yet available at compile time.
--   * All FOR loops use named cursors from RESULTSETs — inline FOR cursors do NOT
--     support field access by name (e.g. rec.COLUMN_NAME fails silently).
--   * COALESCE always appends ', NULL' to handle single-pivot-view deployments.
--   * Step 7 reads from the config table, NOT INFORMATION_SCHEMA, because views
--     created earlier in the same proc are not visible in INFORMATION_SCHEMA
--     until the transaction commits. DIMENSIONS also use config table for same reason.
--
-- PIVOT COLUMN QUOTING REFERENCE:
--   Snowflake PIVOT produces columns with SINGLE QUOTES in their names.
--   e.g., PIVOT(... FOR FIELD_NAME IN ('MRN', 'PATIENT_NAME'))
--   creates columns literally named 'MRN' and 'PATIENT_NAME' (with quotes).
--   To reference these in a SELECT, use DOUBLE-QUOTED identifiers
--   containing the single quotes:  "'MRN'", "'PATIENT_NAME'"
--   The LISTAGG below must produce:  "'MRN'" AS MRN, "'PATIENT_NAME'" AS PATIENT_NAME
--   Inside this proc (single $$ body, no nesting):
--     Target SQL:   "'MRN'" AS MRN
--     Inside ':     '''' || FIELD_NAME || ''''   (two levels of '' escaping)
-- =============================================================================
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- >>> AGENT: DO NOT EXECUTE THIS CREATE PROCEDURE BLOCK.
-- >>> IT WILL FAIL EVERY TIME VIA snowflake_sql_execute. TWO KNOWN BLOCKERS:
-- >>>   1. EXECUTE IMMEDIATE '...' INTO :var  → "unexpected 'INTO'"  (Constraint #16)
-- >>>   2. IDENTIFIER(v_fqn || '...')          → "unexpected 'v_fqn'" (Constraint #17)
-- >>>
-- >>> INSTEAD: Read each numbered sub-step (0 through 7b) below as a TEMPLATE.
-- >>> For each sub-step, write a standalone SQL statement:
-- >>>   - Replace :v_fqn  → '{db}.{schema}'
-- >>>   - Replace :v_db   → '{db}'
-- >>>   - Replace :v_stage_fqn → '{db}.{schema}.{stage}'
-- >>>   - For cursor loops (Step 3, 6, 7), query the config table first to get
-- >>>     the rows, then execute each iteration's SQL individually.
-- >>> Execute each via snowflake_sql_execute — they are plain SQL, no $$ needed.
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- =============================================================================
-- TEMPLATE ONLY — The CREATE PROCEDURE below is for Snowsight worksheet
-- execution. CoCo agents must decompose into individual SQL statements.
-- =============================================================================

CREATE OR REPLACE PROCEDURE IDENTIFIER($V_DB || '.' || $V_SCHEMA || '.GENERATE_DYNAMIC_OBJECTS')(P_DB VARCHAR, P_SCHEMA VARCHAR, P_WAREHOUSE VARCHAR, P_STAGE VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_db VARCHAR;
    v_schema VARCHAR;
    v_warehouse VARCHAR;
    v_stage VARCHAR;
    v_fqn VARCHAR;
    v_stage_fqn VARCHAR;
    v_ddl VARCHAR;
    v_view_name VARCHAR;
    v_doc_type VARCHAR;
    v_field_list VARCHAR;
    v_pivot_in_list VARCHAR;
    v_select_list VARCHAR;
    v_col_def_list VARCHAR;
    v_join_clauses_non_split VARCHAR DEFAULT '';
    v_join_clauses_split VARCHAR DEFAULT '';
    v_coalesce_patient VARCHAR DEFAULT '';
    v_coalesce_mrn VARCHAR DEFAULT '';
    v_view_alias VARCHAR;
    v_alias_counter NUMBER DEFAULT 0;
    v_msg VARCHAR DEFAULT '';
    v_patient_field VARCHAR;
    v_mrn_field VARCHAR;
    v_sv_tables VARCHAR DEFAULT '';
    v_sv_relationships VARCHAR DEFAULT '';
    v_sv_dimensions VARCHAR DEFAULT '';
    v_sv_metrics VARCHAR DEFAULT '';
    v_first_pv VARCHAR DEFAULT '';
    v_dup_count NUMBER DEFAULT 0;
    -- NO cursors in DECLARE — they use RESULTSET pattern in BEGIN
    -- to avoid the limitation where DECLARE cursors cannot reference variables.

BEGIN
    v_db := P_DB;
    v_schema := P_SCHEMA;
    v_warehouse := P_WAREHOUSE;
    v_stage := P_STAGE;
    v_fqn := v_db || '.' || v_schema;
    v_stage_fqn := v_db || '.' || v_schema || '.' || v_stage;

    -- =====================================================================
    -- 0. DEDUPLICATE MASTER CONFIG TABLE
    --    Duplicates arise from repeated CSV loads, re-running Step 1 INSERTs,
    --    or partial re-configurations. Clean before seeding downstream tables.
    -- =====================================================================
    EXECUTE IMMEDIATE '
        SELECT COUNT(*) FROM (
            SELECT CONFIG_TYPE, DOC_TYPE, FIELD_NAME
            FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG
            GROUP BY CONFIG_TYPE, DOC_TYPE, FIELD_NAME
            HAVING COUNT(*) > 1
        )' INTO :v_dup_count;

    IF (v_dup_count > 0) THEN
        EXECUTE IMMEDIATE '
            DELETE FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG
            WHERE ROWID NOT IN (
                SELECT MAX(ROWID)
                FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG
                GROUP BY CONFIG_TYPE, DOC_TYPE, FIELD_NAME
            )';
        v_msg := 'Cleaned ' || v_dup_count || ' duplicate config group(s). ';
    END IF;

    -- =====================================================================
    -- 1. SEED CLASSIFICATION CONFIG from extraction_config (CLASSIFICATION rows)
    -- =====================================================================
    EXECUTE IMMEDIATE '
        DELETE FROM ' || :v_fqn || '.DOCUMENT_CLASSIFICATION_EXTRACTION_FIELD_CONFIG';

    EXECUTE IMMEDIATE '
        INSERT INTO ' || :v_fqn || '.DOCUMENT_CLASSIFICATION_EXTRACTION_FIELD_CONFIG
            (FIELD_NAME, EXTRACTION_QUESTION, TARGET_COLUMN, DATA_TYPE, IS_ACTIVE, DISPLAY_ORDER, CREATED_TIMESTAMP, UPDATED_TIMESTAMP)
        SELECT
            FIELD_NAME,
            EXTRACTION_QUESTION,
            TARGET_COLUMN,
            DATA_TYPE,
            TRUE,
            DISPLAY_ORDER,
            CURRENT_TIMESTAMP(),
            CURRENT_TIMESTAMP()
        FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG
        WHERE CONFIG_TYPE = ''CLASSIFICATION''
        ORDER BY DISPLAY_ORDER';

    v_msg := 'Seeded classification config. ';

    -- =====================================================================
    -- 2. SEED TYPE-SPECIFIC EXTRACTION CONFIG (EXTRACTION rows)
    -- =====================================================================
    EXECUTE IMMEDIATE '
        DELETE FROM ' || :v_fqn || '.DOC_TYPE_SPECIFIC_EXTRACTION_CONFIG';

    EXECUTE IMMEDIATE '
        INSERT INTO ' || :v_fqn || '.DOC_TYPE_SPECIFIC_EXTRACTION_CONFIG
            (DOCUMENT_CLASSIFICATION, FIELD_NAME, EXTRACTION_QUESTION, DATA_TYPE, IS_ACTIVE, DISPLAY_ORDER, CREATED_TIMESTAMP, UPDATED_TIMESTAMP)
        SELECT
            DOC_TYPE,
            FIELD_NAME,
            EXTRACTION_QUESTION,
            DATA_TYPE,
            TRUE,
            DISPLAY_ORDER,
            CURRENT_TIMESTAMP(),
            CURRENT_TIMESTAMP()
        FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG
        WHERE CONFIG_TYPE = ''EXTRACTION''
        ORDER BY DOC_TYPE, DISPLAY_ORDER';

    v_msg := v_msg || 'Seeded type-specific extraction config. ';

    -- =====================================================================
    -- 2b. UPDATE CLASSIFICATION QUESTION with dynamic type list via LISTAGG
    -- =====================================================================
    EXECUTE IMMEDIATE '
        UPDATE ' || :v_fqn || '.DOCUMENT_CLASSIFICATION_EXTRACTION_FIELD_CONFIG
        SET EXTRACTION_QUESTION = ''HOW WOULD YOU CLASSIFY THIS DOCUMENT? CHOOSE STRICTLY ONE VALUE FROM THIS LIST: (''
            || (SELECT LISTAGG(DISTINCT DOC_TYPE, '', '') WITHIN GROUP (ORDER BY DOC_TYPE)
                FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG
                WHERE CONFIG_TYPE = ''EXTRACTION'')
            || '', OTHER)'',
            UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()
        WHERE FIELD_NAME = ''DOCUMENT_CLASSIFICATION''';

    v_msg := v_msg || 'Updated classification question via LISTAGG. ';

    -- =====================================================================
    -- 3. GENERATE PIVOT VIEWS dynamically for each doc type
    --    Uses IS_IDENTITY_FIELD for configurable identity columns
    -- =====================================================================
    LET pivot_rs RESULTSET := (EXECUTE IMMEDIATE
        'SELECT DISTINCT VIEW_NAME, DOC_TYPE FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG WHERE CONFIG_TYPE = ''EXTRACTION'' AND VIEW_NAME IS NOT NULL AND VIEW_NAME != '''' ORDER BY VIEW_NAME');
    LET pivot_cur CURSOR FOR pivot_rs;
    FOR pivot_rec IN pivot_cur DO
        v_view_name := pivot_rec.VIEW_NAME;
        v_doc_type := pivot_rec.DOC_TYPE;
        v_alias_counter := v_alias_counter + 1;
        v_view_alias := 'pv' || v_alias_counter::VARCHAR;

        SELECT
            LISTAGG(FIELD_NAME, ', ') WITHIN GROUP (ORDER BY DISPLAY_ORDER),
            LISTAGG('''' || FIELD_NAME || '''', ', ') WITHIN GROUP (ORDER BY DISPLAY_ORDER),
            LISTAGG(
                CASE WHEN FIELD_NAME = 'PATIENT_NAME' THEN 'UPPER("' || FIELD_NAME || '")' || ' AS ' || FIELD_NAME
                ELSE '"' || FIELD_NAME || '"' || ' AS ' || FIELD_NAME END,
                ', '
            ) WITHIN GROUP (ORDER BY DISPLAY_ORDER)
        INTO :v_field_list, :v_pivot_in_list, :v_select_list
        FROM IDENTIFIER(v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG')
        WHERE CONFIG_TYPE = 'EXTRACTION'
        AND VIEW_NAME = :v_view_name;

        v_col_def_list := 'DOCUMENT_RELATIVE_PATH, DOCUMENT_STAGE, ' || v_field_list;

        v_ddl := '
        CREATE OR REPLACE VIEW ' || v_fqn || '.' || v_view_name || '(' || v_col_def_list || ') AS
        SELECT DOCUMENT_RELATIVE_PATH, DOCUMENT_STAGE, ' || v_select_list || '
        FROM (
            SELECT DOCUMENT_RELATIVE_PATH, DOCUMENT_STAGE, FIELD_NAME, FIELD_VALUE
            FROM ' || v_fqn || '.DOC_TYPE_SPECIFIC_VALUES_EXTRACT_OUTPUT
            WHERE DOCUMENT_CLASSIFICATION = ''' || v_doc_type || '''
        ) PIVOT (MAX(FIELD_VALUE) FOR FIELD_NAME IN (' || v_pivot_in_list || '))';

        EXECUTE IMMEDIATE :v_ddl;

        v_join_clauses_non_split := v_join_clauses_non_split ||
            ' LEFT JOIN ' || v_fqn || '.' || v_view_name || ' ' || v_view_alias ||
            ' ON s.DOCUMENT_RELATIVE_PATH = ' || v_view_alias || '.DOCUMENT_RELATIVE_PATH';

        v_join_clauses_split := v_join_clauses_split ||
            ' LEFT JOIN ' || v_fqn || '.' || v_view_name || ' ' || v_view_alias ||
            ' ON s.PARENT_DOCUMENT_RELATIVE_PATH = ' || v_view_alias || '.DOCUMENT_RELATIVE_PATH';

        SELECT
            COALESCE(MAX(CASE WHEN IS_IDENTITY_FIELD = 'PATIENT_NAME' THEN FIELD_NAME END), 'PATIENT_NAME'),
            COALESCE(MAX(CASE WHEN IS_IDENTITY_FIELD = 'MRN' THEN FIELD_NAME END), 'MRN')
        INTO :v_patient_field, :v_mrn_field
        FROM IDENTIFIER(v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG')
        WHERE CONFIG_TYPE = 'EXTRACTION' AND VIEW_NAME = :v_view_name;

        IF (v_coalesce_patient != '') THEN
            v_coalesce_patient := v_coalesce_patient || ', ';
            v_coalesce_mrn := v_coalesce_mrn || ', ';
        END IF;
        v_coalesce_patient := v_coalesce_patient || v_view_alias || '.' || v_patient_field;
        v_coalesce_mrn := v_coalesce_mrn || v_view_alias || '.' || v_mrn_field;

        v_sv_tables := v_sv_tables ||
            CASE WHEN v_sv_tables != '' THEN ',' ELSE '' END ||
            CHR(10) || '        ' || v_fqn || '.' || v_view_name ||
            CHR(10) || '            COMMENT = ''' || v_doc_type || ' pivot view with extracted fields.'' ';

        v_sv_relationships := v_sv_relationships ||
            CASE WHEN v_sv_relationships != '' THEN ',' ELSE '' END ||
            CHR(10) || '        MRN_TO_' || v_view_name ||
            ' AS ' || v_view_name || '(' || v_mrn_field || ') REFERENCES MRN_PATIENT_MAPPING(MRN)';

        v_msg := v_msg || 'Created view ' || v_view_name || '. ';
    END FOR;

    -- =====================================================================
    -- 4. GENERATE MRN_PATIENT_MAPPING VIEW (simple: from RAW_CONTENT)
    -- =====================================================================
    v_ddl := '
    CREATE OR REPLACE VIEW ' || v_fqn || '.MRN_PATIENT_MAPPING AS
    SELECT DISTINCT MRN, PATIENT_NAME
    FROM ' || v_fqn || '.CLINICAL_DOCUMENTS_RAW_CONTENT
    WHERE MRN IS NOT NULL AND PATIENT_NAME IS NOT NULL';

    EXECUTE IMMEDIATE :v_ddl;
    v_msg := v_msg || 'Created MRN_PATIENT_MAPPING. ';

    -- =====================================================================
    -- 5. GENERATE REFRESH TASK with dynamic JOINs
    --    COALESCE always includes ', NULL' to guarantee 2+ args even with
    --    a single pivot view (prevents Error 8: COALESCE needs 2+ args).
    -- =====================================================================
    v_ddl := '
    CREATE OR REPLACE TASK ' || v_fqn || '.REFRESH_RAW_CONTENT_TASK
        WAREHOUSE = ' || v_warehouse || '
        SCHEDULE = ''99 HOUR''
        COMMENT = ''Incrementally insert new parsed documents and refresh presigned URLs''
        WHEN SYSTEM$STREAM_HAS_DATA(''' || v_fqn || '.DOCS_PARSE_OUTPUT_STREAM'')
    AS
    BEGIN
        CREATE TEMPORARY TABLE IF NOT EXISTS ' || v_fqn || '.TEMP_STREAM_SNAPSHOT AS
        SELECT * FROM ' || v_fqn || '.DOCS_PARSE_OUTPUT_STREAM;

        INSERT INTO ' || v_fqn || '.CLINICAL_DOCUMENTS_RAW_CONTENT (
            DOCUMENT_RELATIVE_PATH, DOCUMENT_STAGE, PAGE_NUMBER_IN_PARENT,
            DOCUMENT_CLASSIFICATION,
            PATIENT_NAME, MRN, PAGE_CONTENT, DOC_TOTAL_PAGES,
            PRESIGNED_URL, STAGE_FILE_URL, URL_GENERATED_AT
        )
        SELECT
            s.DOCUMENT_RELATIVE_PATH, s.DOCUMENT_STAGE, s.PAGE_NUMBER_IN_PARENT,
            dcm_cls.FIELD_VALUE AS DOCUMENT_CLASSIFICATION,
            COALESCE(' || v_coalesce_patient || ', NULL) AS PATIENT_NAME,
            COALESCE(' || v_coalesce_mrn || ', NULL) AS MRN,
            CONCAT(''[Page '', s.PAGE_NUMBER_IN_PARENT, '']'' || CHR(10) || CHR(10), s.PAGE_CONTENT) AS PAGE_CONTENT,
            s.DOC_TOTAL_PAGES,
            GET_PRESIGNED_URL(@' || v_stage_fqn || ', s.DOCUMENT_RELATIVE_PATH, 604800) AS PRESIGNED_URL,
            CONCAT(''snow://stage/'', REPLACE(s.DOCUMENT_STAGE, ''@'', ''''), ''/'', s.DOCUMENT_RELATIVE_PATH) AS STAGE_FILE_URL,
            CURRENT_TIMESTAMP() AS URL_GENERATED_AT
        FROM ' || v_fqn || '.TEMP_STREAM_SNAPSHOT s
        LEFT JOIN ' || v_fqn || '.DOC_CLASSIFICATION_METADATA_ROWS dcm_cls
            ON s.DOCUMENT_RELATIVE_PATH = dcm_cls.DOCUMENT_RELATIVE_PATH
            AND dcm_cls.FIELD_NAME = ''DOCUMENT_CLASSIFICATION'''
        || v_join_clauses_non_split ||
        ' WHERE s.PARENT_DOCUMENT_RELATIVE_PATH IS NULL;

        INSERT INTO ' || v_fqn || '.CLINICAL_DOCUMENTS_RAW_CONTENT (
            DOCUMENT_RELATIVE_PATH, DOCUMENT_STAGE, PAGE_NUMBER_IN_PARENT,
            DOCUMENT_CLASSIFICATION,
            PATIENT_NAME, MRN, PAGE_CONTENT, DOC_TOTAL_PAGES,
            PRESIGNED_URL, STAGE_FILE_URL, URL_GENERATED_AT
        )
        SELECT
            s.PARENT_DOCUMENT_RELATIVE_PATH AS DOCUMENT_RELATIVE_PATH,
            dh.PARENT_DOCUMENT_STAGE AS DOCUMENT_STAGE,
            s.PAGE_NUMBER_IN_PARENT,
            dcm_cls.FIELD_VALUE AS DOCUMENT_CLASSIFICATION,
            COALESCE(' || v_coalesce_patient || ', NULL) AS PATIENT_NAME,
            COALESCE(' || v_coalesce_mrn || ', NULL) AS MRN,
            CONCAT(''[Page '', s.PAGE_NUMBER_IN_PARENT, '']'' || CHR(10) || CHR(10), s.PAGE_CONTENT) AS PAGE_CONTENT,
            s.DOC_TOTAL_PAGES,
            GET_PRESIGNED_URL(@' || v_stage_fqn || ', s.PARENT_DOCUMENT_RELATIVE_PATH, 604800) AS PRESIGNED_URL,
            CONCAT(''snow://stage/'', REPLACE(dh.PARENT_DOCUMENT_STAGE, ''@'', ''''), ''/'', s.PARENT_DOCUMENT_RELATIVE_PATH) AS STAGE_FILE_URL,
            CURRENT_TIMESTAMP() AS URL_GENERATED_AT
        FROM ' || v_fqn || '.TEMP_STREAM_SNAPSHOT s
        JOIN ' || v_fqn || '.DOCUMENT_HIERARCHY dh
            ON s.DOCUMENT_RELATIVE_PATH = dh.DOCUMENT_RELATIVE_PATH AND s.DOCUMENT_STAGE = dh.DOCUMENT_STAGE
        LEFT JOIN ' || v_fqn || '.DOC_CLASSIFICATION_METADATA_ROWS dcm_cls
            ON s.PARENT_DOCUMENT_RELATIVE_PATH = dcm_cls.DOCUMENT_RELATIVE_PATH
            AND dcm_cls.FIELD_NAME = ''DOCUMENT_CLASSIFICATION'''
        || v_join_clauses_split ||
        ' WHERE s.PARENT_DOCUMENT_RELATIVE_PATH IS NOT NULL;

        DROP TABLE IF EXISTS ' || v_fqn || '.TEMP_STREAM_SNAPSHOT;

        UPDATE ' || v_fqn || '.CLINICAL_DOCUMENTS_RAW_CONTENT
        SET PRESIGNED_URL = GET_PRESIGNED_URL(@' || v_stage_fqn || ', DOCUMENT_RELATIVE_PATH, 604800),
            URL_GENERATED_AT = CURRENT_TIMESTAMP()
        WHERE URL_GENERATED_AT < DATEADD(''day'', -6, CURRENT_TIMESTAMP());
    END';

    EXECUTE IMMEDIATE :v_ddl;
    v_msg := v_msg || 'Created REFRESH_RAW_CONTENT_TASK. ';

    -- =====================================================================
    -- 6. GENERATE SEMANTIC VIEW from all discovered pivot views
    --    IMPORTANT: A semantic view REQUIRES at least one DIMENSIONS or
    --    METRICS clause. TABLES + RELATIONSHIPS alone produces:
    --    "No queryable expression is defined in the semantic view."
    --    See: https://docs.snowflake.com/en/sql-reference/sql/create-semantic-view
    --
    --    DIMENSIONS are built from the config table (NOT INFORMATION_SCHEMA)
    --    because views created earlier in this proc are not yet committed.
    --
    --    ⚠️ CRITICAL — DIMENSIONS SYNTAX IS REVERSED FROM NORMAL SQL:
    --       Format:  TABLE_REF.NEW_DIMENSION_NAME AS EXISTING_COLUMN_NAME
    --       The NEW name is on the LEFT of AS, the EXISTING column on the RIGHT.
    --       This is the OPPOSITE of standard SQL (SELECT col AS alias).
    --       Example: DISCHARGE_SUMMARY_V.DS_MRN AS MRN
    --                (DS_MRN = new dimension, MRN = physical column in the view)
    --       WRONG:   TABLE.MRN AS DS_MRN → "invalid identifier" (DS_MRN not a column)
    -- =====================================================================
    IF (v_sv_tables != '') THEN
        -- Build DIMENSIONS from config table (dynamic RESULTSET cursor)
        LET dim_rs RESULTSET := (EXECUTE IMMEDIATE
            'SELECT VIEW_NAME, FIELD_NAME, DOC_TYPE FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG WHERE CONFIG_TYPE = ''EXTRACTION'' ORDER BY VIEW_NAME, DISPLAY_ORDER');
        LET dim_cur CURSOR FOR dim_rs;
        FOR dim_rec IN dim_cur DO
            IF (v_sv_dimensions != '') THEN
                v_sv_dimensions := v_sv_dimensions || ',';
            END IF;
            v_sv_dimensions := v_sv_dimensions ||
                CHR(10) || '        ' || dim_rec.VIEW_NAME || '.' ||
                dim_rec.FIELD_NAME || '_DIM AS ' || dim_rec.FIELD_NAME ||
                CHR(10) || '            COMMENT = ''Extracted ' ||
                REPLACE(dim_rec.FIELD_NAME, '_', ' ') || ' field''';
        END FOR;

        -- Add document path dimensions for each pivot view (dynamic RESULTSET cursor)
        LET pv_dim_rs RESULTSET := (EXECUTE IMMEDIATE
            'SELECT DISTINCT VIEW_NAME FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG WHERE CONFIG_TYPE = ''EXTRACTION'' AND VIEW_NAME IS NOT NULL ORDER BY VIEW_NAME');
        LET pv_dim_cur CURSOR FOR pv_dim_rs;
        FOR pv_rec IN pv_dim_cur DO
            IF (v_sv_dimensions != '') THEN
                v_sv_dimensions := v_sv_dimensions || ',';
            END IF;
            v_sv_dimensions := v_sv_dimensions ||
                CHR(10) || '        ' || pv_rec.VIEW_NAME || '.DOC_PATH AS DOCUMENT_RELATIVE_PATH' ||
                CHR(10) || '            COMMENT = ''Path to source document''';
        END FOR;

        -- Add MRN_PATIENT_MAPPING dimensions
        IF (v_sv_dimensions != '') THEN
            v_sv_dimensions := v_sv_dimensions || ',';
        END IF;
        v_sv_dimensions := v_sv_dimensions ||
            CHR(10) || '        MRN_PATIENT_MAPPING.MRN_KEY AS MRN' ||
            CHR(10) || '            COMMENT = ''Medical record number'',';
        v_sv_dimensions := v_sv_dimensions ||
            CHR(10) || '        MRN_PATIENT_MAPPING.PATIENT_NAME_MAP AS PATIENT_NAME' ||
            CHR(10) || '            COMMENT = ''Patient name from mapping''';

        -- Build METRICS using the first pivot view
        SELECT MIN(VIEW_NAME) INTO :v_first_pv
        FROM IDENTIFIER(v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG')
        WHERE CONFIG_TYPE = 'EXTRACTION' AND VIEW_NAME IS NOT NULL;

        IF (v_first_pv != '') THEN
            v_sv_metrics := '
        ' || v_first_pv || '.PATIENT_COUNT AS COUNT(DISTINCT MRN)
            COMMENT = ''Count of distinct patients'',
        ' || v_first_pv || '.DOCUMENT_COUNT AS COUNT(DISTINCT DOCUMENT_RELATIVE_PATH)
            COMMENT = ''Count of distinct documents''';
        END IF;

        BEGIN
            v_ddl := '
            CREATE OR REPLACE SEMANTIC VIEW ' || v_fqn || '.CLINICAL_DOCS_SEMANTIC_VIEW
                TABLES (' ||
                    v_sv_tables || ',' ||
                    CHR(10) || '        MRN_PATIENT_MAPPING AS ' || v_fqn || '.MRN_PATIENT_MAPPING PRIMARY KEY (MRN)' ||
                    CHR(10) || '            COMMENT = ''Distinct MRN-to-patient-name mapping.''' ||
                CHR(10) || '    )' ||
                CHR(10) || '    RELATIONSHIPS (' ||
                    v_sv_relationships ||
                CHR(10) || '    )' ||
                CHR(10) || '    DIMENSIONS (' ||
                    v_sv_dimensions ||
                CHR(10) || '    )' ||
                CHR(10) || '    METRICS (' ||
                    v_sv_metrics ||
                CHR(10) || '    )' ||
                CHR(10) || '    COMMENT = ''Semantic view for clinical document natural language analytics''';

            EXECUTE IMMEDIATE :v_ddl;
            v_msg := v_msg || 'Created CLINICAL_DOCS_SEMANTIC_VIEW with ' || v_alias_counter || ' pivot views. ';
        EXCEPTION
            WHEN OTHER THEN
                v_msg := v_msg || 'Semantic View creation deferred (pivot views may be empty). Re-run GENERATE_DYNAMIC_OBJECTS() after data is loaded. Error: ' || SQLERRM || '. ';
        END;
    END IF;

    -- =====================================================================
    -- 7. REFRESH SCHEMA CKE (DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_MODEL_REFERENCE)
    --    Views created earlier in this proc are NOT visible in INFORMATION_SCHEMA
    --    until the transaction commits. The config table is the source of truth.
    --    CLINICAL_DOCS_MODEL_SEARCH_SVC auto-refreshes from this table (TARGET_LAG=1d).
    -- =====================================================================
    BEGIN
        LET v_dm_fqn VARCHAR := v_db || '.DATA_MODEL_KNOWLEDGE';
        EXECUTE IMMEDIATE '
            DELETE FROM ' || :v_dm_fqn || '.CLINICAL_DOCS_MODEL_REFERENCE';

        EXECUTE IMMEDIATE '
            INSERT INTO ' || :v_dm_fqn || '.CLINICAL_DOCS_MODEL_REFERENCE
                (SEARCH_TEXT, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DOMAIN_TAG, CATEGORY, DESCRIPTION, CONSTRAINTS, CONTAINS_PHI, RELATIONSHIPS)
            SELECT
                cfg.DOC_TYPE || '' '' || cfg.FIELD_NAME || '' '' || cfg.EXTRACTION_QUESTION AS SEARCH_TEXT,
                COALESCE(cfg.VIEW_NAME, ''DOC_TYPE_SPECIFIC_VALUES_EXTRACT_OUTPUT'') AS TABLE_NAME,
                cfg.FIELD_NAME AS COLUMN_NAME,
                COALESCE(cfg.DATA_TYPE, ''VARCHAR'') AS DATA_TYPE,
                NULL AS DOMAIN_TAG,
                CASE
                    WHEN cfg.CONFIG_TYPE = ''CLASSIFICATION'' THEN ''Classification''
                    WHEN cfg.VIEW_NAME IS NOT NULL AND cfg.VIEW_NAME != '''' THEN ''Pivot View''
                    ELSE ''Extraction Output''
                END AS CATEGORY,
                cfg.EXTRACTION_QUESTION AS DESCRIPTION,
                '''' AS CONSTRAINTS,
                CASE
                    WHEN cfg.FIELD_NAME IN (''PATIENT_NAME'', ''MRN'') THEN ''YES''
                    WHEN cfg.FIELD_NAME LIKE ''%DIAGNOSIS%'' OR cfg.FIELD_NAME LIKE ''%FINDING%'' THEN ''POTENTIAL''
                    ELSE ''NO''
                END AS CONTAINS_PHI,
                CASE
                    WHEN cfg.IS_IDENTITY_FIELD IN (''MRN'', ''PATIENT_NAME'') THEN ''Identity: '' || cfg.IS_IDENTITY_FIELD
                    ELSE ''''
                END AS RELATIONSHIPS
            FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG cfg
            ORDER BY cfg.CONFIG_TYPE, cfg.DOC_TYPE, cfg.DISPLAY_ORDER';

        v_msg := v_msg || 'Refreshed DATA_MODEL_KNOWLEDGE from config table. ';
    EXCEPTION
        WHEN OTHER THEN
            v_msg := v_msg || 'Model reference refresh skipped (table may not exist yet). ';
    END;

    -- =====================================================================
    -- 7b. REFRESH SPEC CKE (DATA_MODEL_KNOWLEDGE.CLINICAL_DOCS_SPECS_REFERENCE)
    --     Populates the Spec CKE table from the same config table.
    --     Enables dynamic discovery: "What fields does a discharge summary have?"
    --     CLINICAL_DOCS_SPECS_SEARCH_SVC auto-refreshes from this table (TARGET_LAG=1d).
    --     Source of truth: references/document_type_specs.yaml -> config table -> here
    -- =====================================================================
    BEGIN
        LET v_spec_fqn VARCHAR := v_db || '.DATA_MODEL_KNOWLEDGE';
        EXECUTE IMMEDIATE '
            DELETE FROM ' || :v_spec_fqn || '.CLINICAL_DOCS_SPECS_REFERENCE';

        EXECUTE IMMEDIATE '
            INSERT INTO ' || :v_spec_fqn || '.CLINICAL_DOCS_SPECS_REFERENCE
                (SEARCH_TEXT, DOC_TYPE, FIELD_NAME, EXTRACTION_QUESTION, DATA_TYPE,
                 DISPLAY_ORDER, VIEW_NAME, IS_IDENTITY_FIELD, CONTAINS_PHI, DESCRIPTION)
            SELECT
                cfg.DOC_TYPE || '' '' || cfg.FIELD_NAME || '' '' || cfg.EXTRACTION_QUESTION AS SEARCH_TEXT,
                cfg.DOC_TYPE,
                cfg.FIELD_NAME,
                cfg.EXTRACTION_QUESTION,
                COALESCE(cfg.DATA_TYPE, ''VARCHAR'') AS DATA_TYPE,
                cfg.DISPLAY_ORDER,
                cfg.VIEW_NAME,
                cfg.IS_IDENTITY_FIELD,
                CASE
                    WHEN cfg.FIELD_NAME IN (''PATIENT_NAME'', ''MRN'') THEN ''YES''
                    WHEN cfg.FIELD_NAME LIKE ''%DIAGNOSIS%'' OR cfg.FIELD_NAME LIKE ''%FINDING%'' THEN ''POTENTIAL''
                    ELSE ''NO''
                END AS CONTAINS_PHI,
                cfg.EXTRACTION_QUESTION AS DESCRIPTION
            FROM ' || :v_fqn || '.CLINICAL_DOCS_EXTRACTION_CONFIG cfg
            WHERE cfg.CONFIG_TYPE = ''EXTRACTION''
            ORDER BY cfg.DOC_TYPE, cfg.DISPLAY_ORDER';

        v_msg := v_msg || 'Refreshed Spec CKE (CLINICAL_DOCS_SPECS_REFERENCE). ';
    EXCEPTION
        WHEN OTHER THEN
            v_msg := v_msg || 'Spec CKE refresh skipped (table may not exist yet). ';
    END;

    RETURN v_msg;
END;
$$;

-- =============================================================================
-- END OF DYNAMIC PIPELINE SETUP
-- =============================================================================
-- Next steps (spec-first flow):
-- 1. Define doc types in references/document_type_specs.yaml (authoritative spec)
-- 2. Seed CLINICAL_DOCS_EXTRACTION_CONFIG from specs (INSERT or COPY INTO from CSV)
-- 3. CALL GENERATE_DYNAMIC_OBJECTS('{db}', '{schema}', '{warehouse}', '{stage}')
--    Parameterized — pass the user-chosen db/schema/warehouse/stage.
--    Seeds config, updates classification question, creates pivot views + task +
--    Semantic View, refreshes Schema CKE (model corpus) + Spec CKE (doc type specs)
-- 4. Upload clinical PDFs to stage
-- 5. Create pipeline stored procedures from individual proc_*.sql files:
--    proc_preprocess_clinical_docs.sql, proc_classify_metadata.sql,
--    proc_extract_type_specific.sql, proc_classify_aggregated.sql,
--    proc_extract_with_ai_agg.sql, proc_parse_with_images.sql
--    Replace {db}/{schema}/{stage} tokens with actual values before execution.
--    (Legacy monolithic version: stored_procedures.sql — retained for reference)
--
-- CKE services (created separately — see data-model-knowledge/SKILL.md):
--   - CLINICAL_DOCS_MODEL_SEARCH_SVC  (Schema CKE — over MODEL_REFERENCE table)
--   - CLINICAL_DOCS_SPECS_SEARCH_SVC  (Spec CKE — over SPECS_REFERENCE table)
-- See references/metadata_as_cke.md for the full CKE-driven pattern.
-- =============================================================================
